from __future__ import annotations

import json
import os
import time
from datetime import datetime, timezone
from pathlib import Path

from stock_monitor import jina_history
from stock_monitor.strategy import enrich_analysis

DEFAULT_SYMBOLS = [
    "8306",  # MUFG
    "8316",  # SMFG
    "4661",  # OLC
    "3397",  # Toridoll
    "9020",  # JR East
    "2914",  # JT
    "8593",  # Mitsubishi HC Capital
    "9432",  # NTT
    "9433",  # KDDI
    "1605",  # INPEX
    "1928",  # Sekisui House
    "1478",  # iShares MSCI Japan High Dividend ETF
]


def symbols() -> list[str]:
    raw = os.getenv("KSC_SYMBOLS", "").strip()
    if not raw:
        return DEFAULT_SYMBOLS
    items = []
    for token in raw.replace("\n", ",").split(","):
        code = token.strip().upper().removesuffix(".T")
        if code and code not in items:
            items.append(code)
    return items or DEFAULT_SYMBOLS


def main() -> int:
    output_path = Path(os.getenv("KSC_DATA_PATH", "data/stocks.json"))
    output_path.parent.mkdir(parents=True, exist_ok=True)

    stocks: dict[str, dict] = {}
    errors: dict[str, str] = {}
    watch = symbols()

    for index, code in enumerate(watch):
        try:
            analysis = jina_history.get_long_term_analysis(code)
            enriched = enrich_analysis(analysis)
            stocks[str(enriched["code"])] = enriched
            print(f"OK {code} {enriched['name']} score={enriched['decision']['score']}")
        except Exception as exc:
            errors[code] = f"{type(exc).__name__}: {exc}"
            print(f"ERROR {code}: {errors[code]}")
        if index + 1 < len(watch):
            time.sleep(1.0)

    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "count": len(stocks),
        "stocks": stocks,
        "errors": errors,
        "note": "Daily technical-analysis snapshot generated by GitHub Actions. Not investment advice.",
    }
    output_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {output_path} ({len(stocks)} stocks, {len(errors)} errors)")
    return 0 if stocks else 1


if __name__ == "__main__":
    raise SystemExit(main())
